@BASEURL=http://localhost:9200



## post create a new resource ex: appname/resource/resource-id
POST {{BASEURL}}/myapp/tweet/2 HTTP/1.1
Content-Type: application/json

{
    "tweet": "Jonny",
    "date": "2021-06-12"
}

### get Get all data  (shards,hits etc...)
GET {{BASEURL}}/_search HTTP/1.1

###  GET get resource data ex: appname/resource/resource-id
GET {{BASEURL}}/my-favorite-games/_doc/2


### resource exists? ex: appname/resource/resource-id
HEAD {{BASEURL}}/myapp/tweet/1 HTTP/1.1


### put update resource ex: appname/resource/resource-id
PUT {{BASEURL}}/myapp/tweet/1 HTTP/1.1
Content-Type: application/json

{
    "tweet": "Lucy",
    "gender": "Female",
    "age": 27,
    "date": "2021-06-7"
}